### ISSUE TITLE
No transition

### ISSUE THREAD

**Issue by kelna** [stefanvictora/hue-scheduler#1]
Hi! I set a 100 min transition, yet it doesn't work for some reason. The config file looks like this:

Szoba, Konyhapult, Etkezo, Furdoszoba, WC	07:00	ct:4400	bri:254	tr-before:100min
Szoba, Konyhapult, Etkezo, Furdoszoba, WC	08:15	ct:4400	bri:254	tr-before:30min	on:true
Szoba, Konyhapult, Etkezo, Furdoszoba, WC	20:00	ct:3400	bri:254	tr-before:100min
Szoba, Konyhapult, Etkezo, Furdoszoba, WC	22:00	ct:2200	bri:128	tr-before:100min

But transitions don't work. For example the lights should change colour very slowly starting from 20:20 and reaching 2200 K at 22:00. Instead, all the lights immediately switch from 4400 K to 2200 K exactly at 20:20. Why is this happening? How can I get the expected behaviour?

**Comment by stefanvictora** [comment]
Hi! Thanks for opening the issue, I'm not really using such long transitions, but a quick manual test did not show any problems.

Can you provide a little more details on your usage? I'm curious why your lights would switch from 4400 K to 2200 K, and not from 3400 K to 2200 K. Are your lights continuously on, or are they turned of at some point during the long transitions?

Since Hue Scheduler is just using the native transition feature of the Hue lights, turning them off (via app) at any time during the transition will stop the transition, and the next time the lights are turned on they will use the light settings as if the transition already ended.

Have you tried shorter transitions, or do transitions in general not work for you?

To further support troubleshooting, the content of the log file would also be of interested. To see exactly which API calls Hue Scheduler sends to your bridge, you can turn on full trace logging by providing the -Dlog.level=TRACE JVM parameter (see https://github.com/stefanvictora/hue-scheduler#-dloglevel)

**Comment by stefanvictora** [comment]
Hi, I'm closing this issue now since there have now been several updates to Hue Scheduler that improve the handling of transitions. Should the issue still occur with the newest version, please let me know and I would kindly ask you to provide some additional logs and details about your setup and type of lights. Thanks!
