### ISSUE TITLE
Automatically handle conversion between kelvin and mired color temperature scales

### ISSUE THREAD

**Issue by jryom** [stefanvictora/hue-scheduler#15]
I'd suggest adding support for hue scheduler to automatically handle conversion between mired and kelvin temperature scales in order to make configuration easier. I was surprised to see errors that I had to use a different scale than what I was expecting. The kelvin scale is something most users will probably be familiar with, but I had never heard of mired before.

I am coming from [kelvin](https://github.com/stefanwichmann/kelvin), and there this discrepancy was never presented to me as a user, but handled internally. 

On a related note, another nice feature of [kelvin](https://github.com/stefanwichmann/kelvin) is that it will automatically handle out-of-bounds values for bulbs. Hue White Ambiance (WA) bulbs can go down to 2200 kelvin, whereas the full color bulbs go to 1000. Kelvin will not throw an error if I set 1000 as the temperature for a WA bulb, but will just silently assume I meant 2200 for that given bulb.

I think adopting the same behavior would make configuring hue scheduler easier, especially with a home mixing old, new, WA and color bulbs.

Love the project btw, pretty excited to port over my configuration from Kelvin. I really like the flexibility of hue scheduler.

**Comment by stefanvictora** [comment]
Hi @jryom, thank you for opening the issue, and I'm glad to hear that you're excited about the project! Hue Scheduler actually already supports both Kelvin and Mired (the scale the Hue bridge uses internally) input values for color temperature. That said, I agree--the error message when providing an out-of-range value could be clearer, as it currently displays the supported range in Mired, even if when Kelvin was used as input.

Instead of such an error message like this:

`InvalidColorTemperatureValue: Invalid ct value '1000'. Support integer range for Light 'Color Ambience Light 1': 153-500`

It would be helpful to include the Kelvin values as well:

`InvalidColorTemperatureValue: Invalid ct value '1000'. Supported integer range for Light 'Color Ambience Light 1': 153-500 (6535-2000)`

Regarding a Kelvin value of 1000: The official CT range for color ambience lights is 6500-2000. However, looking at kelvin, I see that lower values are converted to color rather than directly using the light's color temperature setting. Currently, Hue Scheduler doesn't perform such conversion, but I could add such functionality in a future version if it's something you would expect.

Thanks again for your input!

**Comment by jryom** [comment]
Thanks for the clarification!

**Comment by stefanvictora** [comment]
With v0.12.1, Hue Scheduler now supports setting a CT value of 1000 to color lights. Furthermore, it now silently adjusts to the nearest valid CT value if the specified CT is outside that range.
